# Generated by Django 5.2.8 on 2025-11-23 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('meta', models.CharField(blank=True, max_length=250, verbose_name='توضیح کوتاه')),
                ('category', models.CharField(choices=[('contracts', 'درخواست\u200cها'), ('users', 'کاربران'), ('security', 'امنیت'), ('settings', 'تنظیمات')], max_length=20, verbose_name='دسته')),
                ('level', models.CharField(choices=[('success', 'موفق'), ('info', 'اطلاع'), ('warning', 'هشدار'), ('neutral', 'عادی')], default='info', max_length=20, verbose_name='نوع')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ثبت')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='کاربر انجام\u200cدهنده')),
            ],
            options={
                'verbose_name': 'فعالیت',
                'verbose_name_plural': 'فعالیت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
