# Generated by Django 5.2.8 on 2025-12-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدیر سیستم'), ('staff', 'کارشناس'), ('watcher_admin', 'ادمین بیننده')], db_index=True, default='staff', max_length=20, verbose_name='نقش'),
        ),
    ]
