# Generated by Django 5.2.8 on 2025-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(max_length=150, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(db_index=True, help_text='مثال: 09xxxxxxxxx', max_length=14, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('new', 'در انتظار بررسی'), ('in_review', 'در حال بررسی'), ('done', 'رسیدگی شده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('notes', models.TextField(blank=True, help_text='یادداشت\u200cهای تیم آنام درباره این درخواست (برای نمایش به کاربر نیست).', verbose_name='یادداشت داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست Recode',
                'verbose_name_plural': 'درخواست\u200cهای Recode',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['phone'], name='zlink_recod_phone_3243b9_idx'), models.Index(fields=['status', 'created_at'], name='zlink_recod_status_caa156_idx')],
            },
        ),
    ]
