# Generated by Django 5.2.8 on 2025-12-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recode',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='recode',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='مثال: name@example.com', max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddIndex(
            model_name='recode',
            index=models.Index(fields=['email'], name='zlink_recod_email_0115a5_idx'),
        ),
        migrations.AddIndex(
            model_name='recode',
            index=models.Index(fields=['city'], name='zlink_recod_city_bf92e8_idx'),
        ),
    ]
