# Generated by Django 5.2.8 on 2025-12-20 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zlink', '0002_recode_city_recode_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام معرف')),
                ('code', models.SlugField(unique=True, verbose_name='کد معرف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'معرف',
                'verbose_name_plural': 'معرف\u200cها',
            },
        ),
        migrations.AddField(
            model_name='recode',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recode_requests', to='zlink.referrer', verbose_name='معرف'),
        ),
    ]
