# Generated by Django 5.2.8 on 2025-12-16 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('locked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sheet_url', models.URLField(verbose_name='Google Sheet Link')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='worklog.dailyplan')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('task_title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_blocks', to='worklog.dailyplan')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'عضو'), ('manager', 'مدیر پروژه')], default='member', max_length=20)),
                ('can_edit_plan', models.BooleanField(default=True)),
                ('can_submit_report', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='worklog.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('locked_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='worklog.dailyplan')),
                ('project_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_reports', to='worklog.projectmember')),
            ],
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='project_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_plans', to='worklog.projectmember'),
        ),
        migrations.CreateModel(
            name='ReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'انجام نشده'), (1, 'در دست انجام'), (2, 'انجام شده'), (3, 'مسدود شده'), (4, 'ناقص')])),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='worklog.dailyreport')),
                ('schedule_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_entries', to='worklog.dailyscheduleblock')),
            ],
        ),
        migrations.CreateModel(
            name='ReportExtraAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_actions', to='worklog.dailyreport')),
            ],
        ),
        migrations.AddIndex(
            model_name='dailyscheduleblock',
            index=models.Index(fields=['plan', 'start_time'], name='worklog_dai_plan_id_243742_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['user', 'is_active'], name='worklog_pro_user_id_d9adc2_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmember',
            index=models.Index(fields=['project', 'is_active'], name='worklog_pro_project_43554a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['date'], name='worklog_dai_date_5c36f1_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyreport',
            index=models.Index(fields=['project_member', 'date'], name='worklog_dai_project_52730d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together={('project_member', 'date')},
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['date'], name='worklog_dai_date_e79f95_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['project_member', 'date'], name='worklog_dai_project_87874f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('project_member', 'date')},
        ),
        migrations.AddIndex(
            model_name='reportentry',
            index=models.Index(fields=['schedule_block'], name='worklog_rep_schedul_1f1666_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportentry',
            unique_together={('report', 'schedule_block')},
        ),
    ]
