# Generated by Django 5.2.8 on 2025-12-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worklog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_states', to='worklog.dailyachievement')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_states', to='worklog.dailyreport')),
            ],
            options={
                'indexes': [models.Index(fields=['report'], name='worklog_rep_report__75bcd2_idx'), models.Index(fields=['achievement'], name='worklog_rep_achieve_5e7f92_idx')],
                'unique_together': {('report', 'achievement')},
            },
        ),
    ]
