# Generated by Django 5.2.8 on 2025-11-23 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveBigIntegerField(default=0, verbose_name='تعداد بازدید سایت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'آمار سایت',
                'verbose_name_plural': 'آمار سایت',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=14, validators=[django.core.validators.RegexValidator(message='شماره تماس معتبر وارد کنید.', regex='^\\+?\\d{8,14}$')], verbose_name='شماره تماس')),
                ('startup_name', models.CharField(max_length=200, verbose_name='نام استارتاپ / ایده')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('detail', models.TextField(verbose_name='توضیحات کوتاه درباره محصول')),
                ('status', models.CharField(choices=[('new', 'در انتظار بررسی'), ('in_review', 'در حال بررسی'), ('done', 'رسیدگی شده')], db_index=True, default='new', max_length=20, verbose_name='وضعیت')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='خوانده شده؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'درخواست شتاب\u200cدهی / قرارداد',
                'verbose_name_plural': 'درخواست\u200cهای شتاب\u200cدهی / قرارداد',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone'], name='home_contra_phone_3c74f3_idx'), models.Index(fields=['status', 'is_read'], name='home_contra_status_9cd0dc_idx')],
            },
        ),
    ]
