# Generated by Django 5.2.8 on 2025-11-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='email',
        ),
        migrations.AddField(
            model_name='contract',
            name='departments',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='دپارتمان'),
        ),
    ]
