# Generated by Django 5.2.8 on 2025-11-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_contract_email_contract_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='departments',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان'),
        ),
    ]
