# Generated by Django 5.2.8 on 2025-12-11 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پروژه',
                'verbose_name_plural': 'دسته\u200cبندی پروژه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلا: طراحی مسیر رشد، ساختاردهی تیم، سرمایه\u200cگذاری و همراهی مدیریتی', max_length=120, verbose_name='عنوان نقش')),
                ('slug', models.SlugField(allow_unicode=True, help_text='کوتاه و یکتا برای استفاده احتمالی در فیلتر یا API.', max_length=120, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'نقش آنام در پروژه',
                'verbose_name_plural': 'نقش\u200cهای آنام در پروژه\u200cها',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=250)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'مرحله رشد',
                'verbose_name_plural': 'مراحل رشد',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(db_index=True, max_length=150, verbose_name='نام پروژه (فارسی)')),
                ('name_en', models.CharField(blank=True, help_text='برای استفاده در داشبورد، سئو یا برندینگ بین\u200cالمللی.', max_length=150, null=True, verbose_name='نام پروژه (انگلیسی)')),
                ('slug', models.SlugField(allow_unicode=True, help_text='برای URL صفحه جزئیات، مثلا: novapay', max_length=160, unique=True, verbose_name='اسلاگ (آدرس یکتا)')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('paused', 'موقتا متوقف'), ('exited', 'خروج'), ('internal', 'پروژه داخلی')], db_index=True, default='active', max_length=20, verbose_name='وضعیت پروژه در پورتفوی')),
                ('collaboration_model', models.CharField(choices=[('investment', 'سرمایه\u200cگذاری'), ('acceleration', 'شتاب\u200cدهی'), ('both', 'سرمایه\u200cگذاری + شتاب\u200cدهی'), ('consulting', 'مشاوره و همراهی مدیریتی')], default='both', max_length=20, verbose_name='مدل همکاری با آنام')),
                ('short_tagline', models.CharField(help_text='همون جمله کوتاهی که روی کارت و لیست نمایش داده می\u200cشه.', max_length=230, verbose_name='توضیح کوتاه (کارت / لیست)')),
                ('hero_subtitle', models.CharField(help_text='یک جمله کمی توضیحی\u200cتر که زیر عنوان در صفحه جزئیات می\u200cآید.', max_length=300, verbose_name='زیرتیتر در صفحه جزئیات')),
                ('list_summary', models.TextField(blank=True, help_text='در صورت نیاز، توضیح کمی بلندتر برای صفحه لیست. می\u200cتونه خالی بمونه.', verbose_name='خلاصه برای صفحه لیست')),
                ('detail_summary', models.TextField(blank=True, help_text='متن اصلی «چکیده پروژه»؛ می\u200cتونی همون چیزی که الان تو NovaPay نوشتی اینجا بذاری.', verbose_name='خلاصه اصلی در صفحه جزئیات')),
                ('is_featured_home', models.BooleanField(db_index=True, default=False, verbose_name='نمایش در صفحه اصلی؟')),
                ('home_order', models.PositiveSmallIntegerField(default=0, help_text='هرچه عدد کمتر، بالاتر نشان داده می\u200cشود.', verbose_name='ترتیب نمایش در صفحه اصلی')),
                ('list_order', models.PositiveSmallIntegerField(default=0, help_text='ترتیب پیش\u200cفرض در صفحه پورتفوی.', verbose_name='ترتیب نمایش در صفحه لیست')),
                ('image', models.ImageField(help_text='برای کارت صفحه اصلی و صفحه لیست.', upload_to='portfolio/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت در پورتفوی')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectcategory')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.projectstage')),
            ],
            options={
                'verbose_name': 'پروژه پورتفوی',
                'verbose_name_plural': 'پروژه\u200cهای پورتفوی',
                'ordering': ['-is_featured_home', 'home_order', 'list_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='مثلا: تمرکز روی B2B و Enterprise', max_length=180, verbose_name='متن هایلایت')),
                ('icon_class', models.CharField(blank=True, help_text='مثلا: "bi-graph-up-arrow" یا "bi-shield-lock" (اختیاری)', max_length=50, verbose_name='کلاس آیکن (Bootstrap Icon)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='portfolio.portfolioproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'هایلایت پروژه',
                'verbose_name_plural': 'هایلایت\u200cهای پروژه',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='مثلا: رشد متوسط ماهانه GMV', max_length=150, verbose_name='عنوان متریک')),
                ('value', models.CharField(help_text='مثلا: "+۱۸٪" یا "۳.۱x"', max_length=50, verbose_name='مقدار متریک')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='portfolio.portfolioproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'متریک پروژه',
                'verbose_name_plural': 'متریک\u200cهای پروژه',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectJourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(help_text='مثلا: ۱، ۲، ۳ – برای نمایش در دایره طلایی.', verbose_name='شماره مرحله')),
                ('title', models.CharField(help_text='مثلا: تشخیص گلوگاه\u200cهای کلیدی', max_length=150, verbose_name='عنوان مرحله')),
                ('description', models.TextField(help_text='توضیح کوتاه برای هر مرحله، مشابه چیزی که الان در صفحه NovaPay نوشتی.', verbose_name='توضیح مرحله')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_steps', to='portfolio.portfolioproject', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'مرحله مسیر همکاری',
                'verbose_name_plural': 'مراحل مسیر همکاری پروژه',
                'ordering': ['step_number'],
                'unique_together': {('project', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='ProjectRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='portfolio.portfolioproject', verbose_name='پروژه')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='portfolio.projectrole', verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'نقش اختصاص\u200cداده\u200cشده به پروژه',
                'verbose_name_plural': 'نقش\u200cهای اختصاص\u200cداده\u200cشده به پروژه\u200cها',
                'ordering': ['order'],
                'unique_together': {('project', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['slug'], name='portfolio_p_slug_0adcb4_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['category'], name='portfolio_p_categor_a9303d_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['stage'], name='portfolio_p_stage_i_79e06e_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolioproject',
            index=models.Index(fields=['status', 'is_featured_home'], name='portfolio_p_status_40490d_idx'),
        ),
    ]
