# Generated by Django 5.2.8 on 2025-12-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='stage',
        ),
        migrations.RemoveIndex(
            model_name='portfolioproject',
            name='portfolio_p_stage_i_79e06e_idx',
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ProjectStage',
        ),
    ]
