# Generated by Django 5.2.8 on 2025-12-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolioproject_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='icon_class',
            field=models.CharField(blank=True, help_text='مثلاً: "bi-credit-card" یا "bi-cpu"', max_length=50, verbose_name='کلاس آیکن بوت\u200cاسترپ'),
        ),
    ]
